export default [
  {
    name: "Algeria",
    code: "DZ",
    phoneCode: "+213",
    label: "Algeria",
    value: "Algeria",
    flag: "🇩🇿",
  },
  {
    name: "Angola",
    code: "AO",
    phoneCode: "+244",
    label: "Angola",
    value: "Angola",
    flag: "🇦🇴",
  },
  {
    name: "Argentina",
    code: "AR",
    phoneCode: "+54",
    label: "Argentina",
    value: "Argentina",
    flag: "🇦🇷",
  },
  {
    name: "Australia",
    code: "AU",
    phoneCode: "+61",
    label: "Australia",
    value: "Australia",
    flag: "🇦🇺",
  },
  {
    name: "Austria",
    code: "AT",
    phoneCode: "+43",
    label: "Austria",
    value: "Austria",
    flag: "🇦🇹",
  },
  {
    name: "Bangladesh",
    code: "BD",
    phoneCode: "+880",
    label: "Bangladesh",
    value: "Bangladesh",
    flag: "🇧🇩",
  },
  {
    name: "Belgium",
    code: "BE",
    phoneCode: "+32",
    label: "Belgium",
    value: "Belgium",
    flag: "🇧🇪",
  },
  {
    name: "Brazil",
    code: "BR",
    phoneCode: "+55",
    label: "Brazil",
    value: "Brazil",
    flag: "🇧🇷",
  },
  {
    name: "Canada",
    code: "CA",
    phoneCode: "+1",
    label: "Canada",
    value: "Canada",
    flag: "🇨🇦",
  },
  {
    name: "China",
    code: "CN",
    phoneCode: "+86",
    label: "China",
    value: "China",
    flag: "🇨🇳",
  },
  {
    name: "Denmark",
    code: "DK",
    phoneCode: "+45",
    label: "Denmark",
    value: "Denmark",
    flag: "🇩🇰",
  },
  {
    name: "Egypt",
    code: "EG",
    phoneCode: "+20",
    label: "Egypt",
    value: "Egypt",
    flag: "🇪🇬",
  },
  {
    name: "Finland",
    code: "FI",
    phoneCode: "+358",
    label: "Finland",
    value: "Finland",
    flag: "🇫🇮",
  },
  {
    name: "France",
    code: "FR",
    phoneCode: "+33",
    label: "France",
    value: "France",
    flag: "🇫🇷",
  },
  {
    name: "Germany",
    code: "DE",
    phoneCode: "+49",
    label: "Germany",
    value: "Germany",
    flag: "🇩🇪",
  },
  {
    name: "India",
    code: "IN",
    phoneCode: "+91",
    label: "India",
    value: "India",
    flag: "🇮🇳",
  },
  {
    name: "Indonesia",
    code: "ID",
    phoneCode: "+62",
    label: "Indonesia",
    value: "Indonesia",
    flag: "🇮🇩",
  },
  {
    name: "Italy",
    code: "IT",
    phoneCode: "+39",
    label: "Italy",
    value: "Italy",
    flag: "🇮🇹",
  },
  {
    name: "Japan",
    code: "JP",
    phoneCode: "+81",
    label: "Japan",
    value: "Japan",
    flag: "🇯🇵",
  },
  {
    name: "Kenya",
    code: "KE",
    phoneCode: "+254",
    label: "Kenya",
    value: "Kenya",
    flag: "🇰🇪",
  },
  {
    name: "Mexico",
    code: "MX",
    phoneCode: "+52",
    label: "Mexico",
    value: "Mexico",
    flag: "🇲🇽",
  },
  {
    name: "Netherlands",
    code: "NL",
    phoneCode: "+31",
    label: "Netherlands",
    value: "Netherlands",
    flag: "🇳🇱",
  },
  {
    name: "New Zealand",
    code: "NZ",
    phoneCode: "+64",
    label: "New Zealand",
    value: "New Zealand",
    flag: "🇳🇿",
  },
  {
    name: "Nigeria",
    code: "NG",
    phoneCode: "+234",
    label: "Nigeria",
    value: "Nigeria",
    flag: "🇳🇬",
  },
  {
    name: "Norway",
    code: "NO",
    phoneCode: "+47",
    label: "Norway",
    value: "Norway",
    flag: "🇳🇴",
  },
  {
    name: "Philippines",
    code: "PH",
    phoneCode: "+63",
    label: "Philippines",
    value: "Philippines",
    flag: "🇵🇭",
  },
  {
    name: "Poland",
    code: "PL",
    phoneCode: "+48",
    label: "Poland",
    value: "Poland",
    flag: "🇵🇱",
  },
  {
    name: "Portugal",
    code: "PT",
    phoneCode: "+351",
    label: "Portugal",
    value: "Portugal",
    flag: "🇵🇹",
  },
  {
    name: "Russia",
    code: "RU",
    phoneCode: "+7",
    label: "Russia",
    value: "Russia",
    flag: "🇷🇺",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    phoneCode: "+966",
    label: "Saudi Arabia",
    value: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    name: "Singapore",
    code: "SG",
    phoneCode: "+65",
    label: "Singapore",
    value: "Singapore",
    flag: "🇸🇬",
  },
  {
    name: "South Africa",
    code: "ZA",
    phoneCode: "+27",
    label: "South Africa",
    value: "South Africa",
    flag: "🇿🇦",
  },
  {
    name: "South Korea",
    code: "KR",
    phoneCode: "+82",
    label: "South Korea",
    value: "South Korea",
    flag: "🇰🇷",
  },
  {
    name: "Spain",
    code: "ES",
    phoneCode: "+34",
    label: "Spain",
    value: "Spain",
    flag: "🇪🇸",
  },
  {
    name: "Sweden",
    code: "SE",
    phoneCode: "+46",
    label: "Sweden",
    value: "Sweden",
    flag: "🇸🇪",
  },
  {
    name: "Switzerland",
    code: "CH",
    phoneCode: "+41",
    label: "Switzerland",
    value: "Switzerland",
    flag: "🇨🇭",
  },
  {
    name: "Thailand",
    code: "TH",
    phoneCode: "+66",
    label: "Thailand",
    value: "Thailand",
    flag: "🇹🇭",
  },
  {
    name: "Turkey",
    code: "TR",
    phoneCode: "+90",
    label: "Turkey",
    value: "Turkey",
    flag: "🇹🇷",
  },
  {
    name: "Ukraine",
    code: "UA",
    phoneCode: "+380",
    label: "Ukraine",
    value: "Ukraine",
    flag: "🇺🇦",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    phoneCode: "+971",
    label: "United Arab Emirates",
    value: "United Arab Emirates",
    flag: "🇦🇪",
  },
  {
    name: "United Kingdom",
    code: "GB",
    phoneCode: "+44",
    label: "United Kingdom",
    value: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    name: "United States",
    code: "US",
    phoneCode: "+1",
    label: "United States",
    value: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Vietnam",
    code: "VN",
    phoneCode: "+84",
    label: "Vietnam",
    value: "Vietnam",
    flag: "🇻🇳",
  },
  // Continue adding more countries as needed...
];
