export default [
  {
    name: "Afghanistan",
    code: "AF",
    phoneCode: "+93",
    label: "Afghanistan",
    value: "Afghanistan",
    flag: "🇦🇫",
  },
  {
    name: "Albania",
    code: "AL",
    phoneCode: "+355",
    label: "Albania",
    value: "Albania",
    flag: "🇦🇱",
  },
  {
    name: "Algeria",
    code: "DZ",
    phoneCode: "+213",
    label: "Algeria",
    value: "Algeria",
    flag: "🇩🇿",
  },
  {
    name: "Andorra",
    code: "AD",
    phoneCode: "+376",
    label: "Andorra",
    value: "Andorra",
    flag: "🇦🇩",
  },
  {
    name: "Angola",
    code: "AO",
    phoneCode: "+244",
    label: "Angola",
    value: "Angola",
    flag: "🇦🇴",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    phoneCode: "+1-268",
    label: "Antigua and Barbuda",
    value: "Antigua and Barbuda",
    flag: "🇦🇬",
  },
  {
    name: "Argentina",
    code: "AR",
    phoneCode: "+54",
    label: "Argentina",
    value: "Argentina",
    flag: "🇦🇷",
  },
  {
    name: "Armenia",
    code: "AM",
    phoneCode: "+374",
    label: "Armenia",
    value: "Armenia",
    flag: "🇦🇲",
  },
  {
    name: "Australia",
    code: "AU",
    phoneCode: "+61",
    label: "Australia",
    value: "Australia",
    flag: "🇦🇺",
  },
  {
    name: "Austria",
    code: "AT",
    phoneCode: "+43",
    label: "Austria",
    value: "Austria",
    flag: "🇦🇹",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    phoneCode: "+994",
    label: "Azerbaijan",
    value: "Azerbaijan",
    flag: "🇦🇿",
  },
  {
    name: "Bahamas",
    code: "BS",
    phoneCode: "+1-242",
    label: "Bahamas",
    value: "Bahamas",
    flag: "🇧🇸",
  },
  {
    name: "Bahrain",
    code: "BH",
    phoneCode: "+973",
    label: "Bahrain",
    value: "Bahrain",
    flag: "🇧🇭",
  },
  {
    name: "Bangladesh",
    code: "BD",
    phoneCode: "+880",
    label: "Bangladesh",
    value: "Bangladesh",
    flag: "🇧🇩",
  },
  {
    name: "Barbados",
    code: "BB",
    phoneCode: "+1-246",
    label: "Barbados",
    value: "Barbados",
    flag: "🇧🇧",
  },
  {
    name: "Belarus",
    code: "BY",
    phoneCode: "+375",
    label: "Belarus",
    value: "Belarus",
    flag: "🇧🇾",
  },
  {
    name: "Belgium",
    code: "BE",
    phoneCode: "+32",
    label: "Belgium",
    value: "Belgium",
    flag: "🇧🇪",
  },
  {
    name: "Belize",
    code: "BZ",
    phoneCode: "+501",
    label: "Belize",
    value: "Belize",
    flag: "🇧🇿",
  },
  {
    name: "Benin",
    code: "BJ",
    phoneCode: "+229",
    label: "Benin",
    value: "Benin",
    flag: "🇧🇯",
  },
  {
    name: "Bhutan",
    code: "BT",
    phoneCode: "+975",
    label: "Bhutan",
    value: "Bhutan",
    flag: "🇧🇹",
  },
  {
    name: "Bolivia",
    code: "BO",
    phoneCode: "+591",
    label: "Bolivia",
    value: "Bolivia",
    flag: "🇧🇴",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    phoneCode: "+387",
    label: "Bosnia and Herzegovina",
    value: "Bosnia and Herzegovina",
    flag: "🇧🇦",
  },
  {
    name: "Botswana",
    code: "BW",
    phoneCode: "+267",
    label: "Botswana",
    value: "Botswana",
    flag: "🇧🇼",
  },
  {
    name: "Brazil",
    code: "BR",
    phoneCode: "+55",
    label: "Brazil",
    value: "Brazil",
    flag: "🇧🇷",
  },
  {
    name: "Brunei",
    code: "BN",
    phoneCode: "+673",
    label: "Brunei",
    value: "Brunei",
    flag: "🇧🇳",
  },
  {
    name: "Bulgaria",
    code: "BG",
    phoneCode: "+359",
    label: "Bulgaria",
    value: "Bulgaria",
    flag: "🇧🇬",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    phoneCode: "+226",
    label: "Burkina Faso",
    value: "Burkina Faso",
    flag: "🇧🇫",
  },
  {
    name: "Burundi",
    code: "BI",
    phoneCode: "+257",
    label: "Burundi",
    value: "Burundi",
    flag: "🇧🇮",
  },
  {
    name: "Cambodia",
    code: "KH",
    phoneCode: "+855",
    label: "Cambodia",
    value: "Cambodia",
    flag: "🇰🇭",
  },
  {
    name: "Cameroon",
    code: "CM",
    phoneCode: "+237",
    label: "Cameroon",
    value: "Cameroon",
    flag: "🇨🇲",
  },
  {
    name: "Canada",
    code: "CA",
    phoneCode: "+1",
    label: "Canada",
    value: "Canada",
    flag: "🇨🇦",
  },
  {
    name: "Cape Verde",
    code: "CV",
    phoneCode: "+238",
    label: "Cape Verde",
    value: "Cape Verde",
    flag: "🇨🇻",
  },
  {
    name: "Central African Republic",
    code: "CF",
    phoneCode: "+236",
    label: "Central African Republic",
    value: "Central African Republic",
    flag: "🇨🇫",
  },
  {
    name: "Chad",
    code: "TD",
    phoneCode: "+235",
    label: "Chad",
    value: "Chad",
    flag: "🇹🇩",
  },
  {
    name: "Chile",
    code: "CL",
    phoneCode: "+56",
    label: "Chile",
    value: "Chile",
    flag: "🇨🇱",
  },
  {
    name: "China",
    code: "CN",
    phoneCode: "+86",
    label: "China",
    value: "China",
    flag: "🇨🇳",
  },
  {
    name: "Colombia",
    code: "CO",
    phoneCode: "+57",
    label: "Colombia",
    value: "Colombia",
    flag: "🇨🇴",
  },
  {
    name: "Comoros",
    code: "KM",
    phoneCode: "+269",
    label: "Comoros",
    value: "Comoros",
    flag: "🇰🇲",
  },
  {
    name: "Congo",
    code: "CG",
    phoneCode: "+242",
    label: "Congo",
    value: "Congo",
    flag: "🇨🇬",
  },
  {
    name: "Congo (Democratic Republic)",
    code: "CD",
    phoneCode: "+243",
    label: "Congo (DRC)",
    value: "Congo (DRC)",
    flag: "🇨🇩",
  },
  {
    name: "Costa Rica",
    code: "CR",
    phoneCode: "+506",
    label: "Costa Rica",
    value: "Costa Rica",
    flag: "🇨🇷",
  },
  {
    name: "Croatia",
    code: "HR",
    phoneCode: "+385",
    label: "Croatia",
    value: "Croatia",
    flag: "🇭🇷",
  },
  {
    name: "Cuba",
    code: "CU",
    phoneCode: "+53",
    label: "Cuba",
    value: "Cuba",
    flag: "🇨🇺",
  },
  {
    name: "Cyprus",
    code: "CY",
    phoneCode: "+357",
    label: "Cyprus",
    value: "Cyprus",
    flag: "🇨🇾",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    phoneCode: "+420",
    label: "Czech Republic",
    value: "Czech Republic",
    flag: "🇨🇿",
  },
  {
    name: "Denmark",
    code: "DK",
    phoneCode: "+45",
    label: "Denmark",
    value: "Denmark",
    flag: "🇩🇰",
  },
  {
    name: "Djibouti",
    code: "DJ",
    phoneCode: "+253",
    label: "Djibouti",
    value: "Djibouti",
    flag: "🇩🇯",
  },
  {
    name: "Dominica",
    code: "DM",
    phoneCode: "+1-767",
    label: "Dominica",
    value: "Dominica",
    flag: "🇩🇲",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    phoneCode: "+1-809",
    label: "Dominican Republic",
    value: "Dominican Republic",
    flag: "🇩🇴",
  },
  {
    name: "Ecuador",
    code: "EC",
    phoneCode: "+593",
    label: "Ecuador",
    value: "Ecuador",
    flag: "🇪🇨",
  },
  {
    name: "Egypt",
    code: "EG",
    phoneCode: "+20",
    label: "Egypt",
    value: "Egypt",
    flag: "🇪🇬",
  },
  {
    name: "El Salvador",
    code: "SV",
    phoneCode: "+503",
    label: "El Salvador",
    value: "El Salvador",
    flag: "🇸🇻",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    phoneCode: "+240",
    label: "Equatorial Guinea",
    value: "Equatorial Guinea",
    flag: "🇬🇶",
  },
  {
    name: "Eritrea",
    code: "ER",
    phoneCode: "+291",
    label: "Eritrea",
    value: "Eritrea",
    flag: "🇪🇷",
  },
  {
    name: "Estonia",
    code: "EE",
    phoneCode: "+372",
    label: "Estonia",
    value: "Estonia",
    flag: "🇪🇪",
  },
  {
    name: "Eswatini",
    code: "SZ",
    phoneCode: "+268",
    label: "Eswatini",
    value: "Eswatini",
    flag: "🇸🇿",
  },
  {
    name: "Ethiopia",
    code: "ET",
    phoneCode: "+251",
    label: "Ethiopia",
    value: "Ethiopia",
    flag: "🇪🇹",
  },
  {
    name: "Fiji",
    code: "FJ",
    phoneCode: "+679",
    label: "Fiji",
    value: "Fiji",
    flag: "🇫🇯",
  },
  {
    name: "Finland",
    code: "FI",
    phoneCode: "+358",
    label: "Finland",
    value: "Finland",
    flag: "🇫🇮",
  },
  {
    name: "France",
    code: "FR",
    phoneCode: "+33",
    label: "France",
    value: "France",
    flag: "🇫🇷",
  },
  {
    name: "Gabon",
    code: "GA",
    phoneCode: "+241",
    label: "Gabon",
    value: "Gabon",
    flag: "🇬🇦",
  },
  {
    name: "Gambia",
    code: "GM",
    phoneCode: "+220",
    label: "Gambia",
    value: "Gambia",
    flag: "🇬🇲",
  },
  {
    name: "Georgia",
    code: "GE",
    phoneCode: "+995",
    label: "Georgia",
    value: "Georgia",
    flag: "🇬🇪",
  },
  {
    name: "Germany",
    code: "DE",
    phoneCode: "+49",
    label: "Germany",
    value: "Germany",
    flag: "🇩🇪",
  },
  {
    name: "Ghana",
    code: "GH",
    phoneCode: "+233",
    label: "Ghana",
    value: "Ghana",
    flag: "🇬🇭",
  },
  {
    name: "Greece",
    code: "GR",
    phoneCode: "+30",
    label: "Greece",
    value: "Greece",
    flag: "🇬🇷",
  },
  {
    name: "Grenada",
    code: "GD",
    phoneCode: "+1-473",
    label: "Grenada",
    value: "Grenada",
    flag: "🇬🇩",
  },
  {
    name: "Guatemala",
    code: "GT",
    phoneCode: "+502",
    label: "Guatemala",
    value: "Guatemala",
    flag: "🇬🇹",
  },
  {
    name: "Guinea",
    code: "GN",
    phoneCode: "+224",
    label: "Guinea",
    value: "Guinea",
    flag: "🇬🇳",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    phoneCode: "+245",
    label: "Guinea-Bissau",
    value: "Guinea-Bissau",
    flag: "🇬🇼",
  },
  {
    name: "Guyana",
    code: "GY",
    phoneCode: "+592",
    label: "Guyana",
    value: "Guyana",
    flag: "🇬🇾",
  },
  {
    name: "Haiti",
    code: "HT",
    phoneCode: "+509",
    label: "Haiti",
    value: "Haiti",
    flag: "🇭🇹",
  },
  {
    name: "Honduras",
    code: "HN",
    phoneCode: "+504",
    label: "Honduras",
    value: "Honduras",
    flag: "🇭🇳",
  },
  {
    name: "Hungary",
    code: "HU",
    phoneCode: "+36",
    label: "Hungary",
    value: "Hungary",
    flag: "🇭🇺",
  },
  {
    name: "Iceland",
    code: "IS",
    phoneCode: "+354",
    label: "Iceland",
    value: "Iceland",
    flag: "🇮🇸",
  },
  {
    name: "India",
    code: "IN",
    phoneCode: "+91",
    label: "India",
    value: "India",
    flag: "🇮🇳",
  },
  {
    name: "Indonesia",
    code: "ID",
    phoneCode: "+62",
    label: "Indonesia",
    value: "Indonesia",
    flag: "🇮🇩",
  },
  {
    name: "Iran",
    code: "IR",
    phoneCode: "+98",
    label: "Iran",
    value: "Iran",
    flag: "🇮🇷",
  },
  {
    name: "Iraq",
    code: "IQ",
    phoneCode: "+964",
    label: "Iraq",
    value: "Iraq",
    flag: "🇮🇶",
  },
  {
    name: "Ireland",
    code: "IE",
    phoneCode: "+353",
    label: "Ireland",
    value: "Ireland",
    flag: "🇮🇪",
  },
  {
    name: "Israel",
    code: "IL",
    phoneCode: "+972",
    label: "Israel",
    value: "Israel",
    flag: "🇮🇱",
  },
  {
    name: "Italy",
    code: "IT",
    phoneCode: "+39",
    label: "Italy",
    value: "Italy",
    flag: "🇮🇹",
  },
  {
    name: "Jamaica",
    code: "JM",
    phoneCode: "+1-876",
    label: "Jamaica",
    value: "Jamaica",
    flag: "🇯🇲",
  },
  {
    name: "Japan",
    code: "JP",
    phoneCode: "+81",
    label: "Japan",
    value: "Japan",
    flag: "🇯🇵",
  },
  {
    name: "Jordan",
    code: "JO",
    phoneCode: "+962",
    label: "Jordan",
    value: "Jordan",
    flag: "🇯🇴",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    phoneCode: "+7",
    label: "Kazakhstan",
    value: "Kazakhstan",
    flag: "🇰🇿",
  },
  {
    name: "Kenya",
    code: "KE",
    phoneCode: "+254",
    label: "Kenya",
    value: "Kenya",
    flag: "🇰🇪",
  },
  {
    name: "Kiribati",
    code: "KI",
    phoneCode: "+686",
    label: "Kiribati",
    value: "Kiribati",
    flag: "🇰🇮",
  },
  {
    name: "Kuwait",
    code: "KW",
    phoneCode: "+965",
    label: "Kuwait",
    value: "Kuwait",
    flag: "🇰🇼",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    phoneCode: "+996",
    label: "Kyrgyzstan",
    value: "Kyrgyzstan",
    flag: "🇰🇬",
  },
  {
    name: "Laos",
    code: "LA",
    phoneCode: "+856",
    label: "Laos",
    value: "Laos",
    flag: "🇱🇦",
  },
  {
    name: "Latvia",
    code: "LV",
    phoneCode: "+371",
    label: "Latvia",
    value: "Latvia",
    flag: "🇱🇻",
  },
  {
    name: "Lebanon",
    code: "LB",
    phoneCode: "+961",
    label: "Lebanon",
    value: "Lebanon",
    flag: "🇱🇧",
  },
  {
    name: "Lesotho",
    code: "LS",
    phoneCode: "+266",
    label: "Lesotho",
    value: "Lesotho",
    flag: "🇱🇸",
  },
  {
    name: "Liberia",
    code: "LR",
    phoneCode: "+231",
    label: "Liberia",
    value: "Liberia",
    flag: "🇱🇷",
  },
  {
    name: "Libya",
    code: "LY",
    phoneCode: "+218",
    label: "Libya",
    value: "Libya",
    flag: "🇱🇾",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    phoneCode: "+423",
    label: "Liechtenstein",
    value: "Liechtenstein",
    flag: "🇱🇮",
  },
  {
    name: "Lithuania",
    code: "LT",
    phoneCode: "+370",
    label: "Lithuania",
    value: "Lithuania",
    flag: "🇱🇹",
  },
  {
    name: "Luxembourg",
    code: "LU",
    phoneCode: "+352",
    label: "Luxembourg",
    value: "Luxembourg",
    flag: "🇱🇺",
  },
  {
    name: "Madagascar",
    code: "MG",
    phoneCode: "+261",
    label: "Madagascar",
    value: "Madagascar",
    flag: "🇲🇬",
  },
  {
    name: "Malawi",
    code: "MW",
    phoneCode: "+265",
    label: "Malawi",
    value: "Malawi",
    flag: "🇲🇼",
  },
  {
    name: "Malaysia",
    code: "MY",
    phoneCode: "+60",
    label: "Malaysia",
    value: "Malaysia",
    flag: "🇲🇾",
  },
  {
    name: "Maldives",
    code: "MV",
    phoneCode: "+960",
    label: "Maldives",
    value: "Maldives",
    flag: "🇲🇻",
  },
  {
    name: "Mali",
    code: "ML",
    phoneCode: "+223",
    label: "Mali",
    value: "Mali",
    flag: "🇲🇱",
  },
  {
    name: "Malta",
    code: "MT",
    phoneCode: "+356",
    label: "Malta",
    value: "Malta",
    flag: "🇲🇹",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    phoneCode: "+692",
    label: "Marshall Islands",
    value: "Marshall Islands",
    flag: "🇲🇭",
  },
  {
    name: "Mauritania",
    code: "MR",
    phoneCode: "+222",
    label: "Mauritania",
    value: "Mauritania",
    flag: "🇲🇷",
  },
  {
    name: "Mauritius",
    code: "MU",
    phoneCode: "+230",
    label: "Mauritius",
    value: "Mauritius",
    flag: "🇲🇺",
  },
  {
    name: "Mexico",
    code: "MX",
    phoneCode: "+52",
    label: "Mexico",
    value: "Mexico",
    flag: "🇲🇽",
  },
  {
    name: "Micronesia",
    code: "FM",
    phoneCode: "+691",
    label: "Micronesia",
    value: "Micronesia",
    flag: "🇫🇲",
  },
  {
    name: "Moldova",
    code: "MD",
    phoneCode: "+373",
    label: "Moldova",
    value: "Moldova",
    flag: "🇲🇩",
  },
  {
    name: "Monaco",
    code: "MC",
    phoneCode: "+377",
    label: "Monaco",
    value: "Monaco",
    flag: "🇲🇨",
  },
  {
    name: "Mongolia",
    code: "MN",
    phoneCode: "+976",
    label: "Mongolia",
    value: "Mongolia",
    flag: "🇲🇳",
  },
  {
    name: "Montenegro",
    code: "ME",
    phoneCode: "+382",
    label: "Montenegro",
    value: "Montenegro",
    flag: "🇲🇪",
  },
  {
    name: "Morocco",
    code: "MA",
    phoneCode: "+212",
    label: "Morocco",
    value: "Morocco",
    flag: "🇲🇦",
  },
  {
    name: "Mozambique",
    code: "MZ",
    phoneCode: "+258",
    label: "Mozambique",
    value: "Mozambique",
    flag: "🇲🇿",
  },
  {
    name: "Myanmar",
    code: "MM",
    phoneCode: "+95",
    label: "Myanmar",
    value: "Myanmar",
    flag: "🇲🇲",
  },
  {
    name: "Namibia",
    code: "NA",
    phoneCode: "+264",
    label: "Namibia",
    value: "Namibia",
    flag: "🇳🇦",
  },
  {
    name: "Nauru",
    code: "NR",
    phoneCode: "+674",
    label: "Nauru",
    value: "Nauru",
    flag: "🇳🇷",
  },
  {
    name: "Nepal",
    code: "NP",
    phoneCode: "+977",
    label: "Nepal",
    value: "Nepal",
    flag: "🇳🇵",
  },
  {
    name: "Netherlands",
    code: "NL",
    phoneCode: "+31",
    label: "Netherlands",
    value: "Netherlands",
    flag: "🇳🇱",
  },
  {
    name: "New Zealand",
    code: "NZ",
    phoneCode: "+64",
    label: "New Zealand",
    value: "New Zealand",
    flag: "🇳🇿",
  },
  {
    name: "Nicaragua",
    code: "NI",
    phoneCode: "+505",
    label: "Nicaragua",
    value: "Nicaragua",
    flag: "🇳🇮",
  },
  {
    name: "Niger",
    code: "NE",
    phoneCode: "+227",
    label: "Niger",
    value: "Niger",
    flag: "🇳🇪",
  },
  {
    name: "Nigeria",
    code: "NG",
    phoneCode: "+234",
    label: "Nigeria",
    value: "Nigeria",
    flag: "🇳🇬",
  },
  {
    name: "North Korea",
    code: "KP",
    phoneCode: "+850",
    label: "North Korea",
    value: "North Korea",
    flag: "🇰🇵",
  },
  {
    name: "Norway",
    code: "NO",
    phoneCode: "+47",
    label: "Norway",
    value: "Norway",
    flag: "🇳🇴",
  },
  {
    name: "Oman",
    code: "OM",
    phoneCode: "+968",
    label: "Oman",
    value: "Oman",
    flag: "🇴🇲",
  },
  {
    name: "Pakistan",
    code: "PK",
    phoneCode: "+92",
    label: "Pakistan",
    value: "Pakistan",
    flag: "🇵🇰",
  },
  {
    name: "Palau",
    code: "PW",
    phoneCode: "+680",
    label: "Palau",
    value: "Palau",
    flag: "🇵🇼",
  },
  {
    name: "Panama",
    code: "PA",
    phoneCode: "+507",
    label: "Panama",
    value: "Panama",
    flag: "🇵🇦",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    phoneCode: "+675",
    label: "Papua New Guinea",
    value: "Papua New Guinea",
    flag: "🇵🇬",
  },
  {
    name: "Paraguay",
    code: "PY",
    phoneCode: "+595",
    label: "Paraguay",
    value: "Paraguay",
    flag: "🇵🇾",
  },
  {
    name: "Peru",
    code: "PE",
    phoneCode: "+51",
    label: "Peru",
    value: "Peru",
    flag: "🇵🇪",
  },
  {
    name: "Philippines",
    code: "PH",
    phoneCode: "+63",
    label: "Philippines",
    value: "Philippines",
    flag: "🇵🇭",
  },
  {
    name: "Poland",
    code: "PL",
    phoneCode: "+48",
    label: "Poland",
    value: "Poland",
    flag: "🇵🇱",
  },
  {
    name: "Portugal",
    code: "PT",
    phoneCode: "+351",
    label: "Portugal",
    value: "Portugal",
    flag: "🇵🇹",
  },
  {
    name: "Qatar",
    code: "QA",
    phoneCode: "+974",
    label: "Qatar",
    value: "Qatar",
    flag: "🇶🇦",
  },
  {
    name: "Romania",
    code: "RO",
    phoneCode: "+40",
    label: "Romania",
    value: "Romania",
    flag: "🇷🇴",
  },
  {
    name: "Russia",
    code: "RU",
    phoneCode: "+7",
    label: "Russia",
    value: "Russia",
    flag: "🇷🇺",
  },
  {
    name: "Rwanda",
    code: "RW",
    phoneCode: "+250",
    label: "Rwanda",
    value: "Rwanda",
    flag: "🇷🇼",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    phoneCode: "+1869",
    label: "Saint Kitts and Nevis",
    value: "Saint Kitts and Nevis",
    flag: "🇰🇳",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    phoneCode: "+1758",
    label: "Saint Lucia",
    value: "Saint Lucia",
    flag: "🇱🇨",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    phoneCode: "+1784",
    label: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
  },
  {
    name: "Samoa",
    code: "WS",
    phoneCode: "+685",
    label: "Samoa",
    value: "Samoa",
    flag: "🇼🇸",
  },
  {
    name: "San Marino",
    code: "SM",
    phoneCode: "+378",
    label: "San Marino",
    value: "San Marino",
    flag: "🇸🇲",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    phoneCode: "+239",
    label: "Sao Tome and Principe",
    value: "Sao Tome and Principe",
    flag: "🇸🇹",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    phoneCode: "+966",
    label: "Saudi Arabia",
    value: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    name: "Senegal",
    code: "SN",
    phoneCode: "+221",
    label: "Senegal",
    value: "Senegal",
    flag: "🇸🇳",
  },
  {
    name: "Serbia",
    code: "RS",
    phoneCode: "+381",
    label: "Serbia",
    value: "Serbia",
    flag: "🇷🇸",
  },
  {
    name: "Seychelles",
    code: "SC",
    phoneCode: "+248",
    label: "Seychelles",
    value: "Seychelles",
    flag: "🇸🇨",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    phoneCode: "+232",
    label: "Sierra Leone",
    value: "Sierra Leone",
    flag: "🇸🇱",
  },
  {
    name: "Singapore",
    code: "SG",
    phoneCode: "+65",
    label: "Singapore",
    value: "Singapore",
    flag: "🇸🇬",
  },
  {
    name: "Slovakia",
    code: "SK",
    phoneCode: "+421",
    label: "Slovakia",
    value: "Slovakia",
    flag: "🇸🇰",
  },
  {
    name: "Slovenia",
    code: "SI",
    phoneCode: "+386",
    label: "Slovenia",
    value: "Slovenia",
    flag: "🇸🇮",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    phoneCode: "+677",
    label: "Solomon Islands",
    value: "Solomon Islands",
    flag: "🇸🇧",
  },
  {
    name: "Somalia",
    code: "SO",
    phoneCode: "+252",
    label: "Somalia",
    value: "Somalia",
    flag: "🇸🇴",
  },
  {
    name: "South Africa",
    code: "ZA",
    phoneCode: "+27",
    label: "South Africa",
    value: "South Africa",
    flag: "🇿🇦",
  },
  {
    name: "South Korea",
    code: "KR",
    phoneCode: "+82",
    label: "South Korea",
    value: "South Korea",
    flag: "🇰🇷",
  },
  {
    name: "South Sudan",
    code: "SS",
    phoneCode: "+211",
    label: "South Sudan",
    value: "South Sudan",
    flag: "🇸🇸",
  },
  {
    name: "Spain",
    code: "ES",
    phoneCode: "+34",
    label: "Spain",
    value: "Spain",
    flag: "🇪🇸",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    phoneCode: "+94",
    label: "Sri Lanka",
    value: "Sri Lanka",
    flag: "🇱🇰",
  },
  {
    name: "Sudan",
    code: "SD",
    phoneCode: "+249",
    label: "Sudan",
    value: "Sudan",
    flag: "🇸🇩",
  },
  {
    name: "Suriname",
    code: "SR",
    phoneCode: "+597",
    label: "Suriname",
    value: "Suriname",
    flag: "🇸🇷",
  },
  {
    name: "Swaziland",
    code: "SZ",
    phoneCode: "+268",
    label: "Swaziland",
    value: "Swaziland",
    flag: "🇸🇿",
  },
  {
    name: "Sweden",
    code: "SE",
    phoneCode: "+46",
    label: "Sweden",
    value: "Sweden",
    flag: "🇸🇪",
  },
  {
    name: "Switzerland",
    code: "CH",
    phoneCode: "+41",
    label: "Switzerland",
    value: "Switzerland",
    flag: "🇨🇭",
  },
  {
    name: "Syria",
    code: "SY",
    phoneCode: "+963",
    label: "Syria",
    value: "Syria",
    flag: "🇸🇾",
  },
  {
    name: "Taiwan",
    code: "TW",
    phoneCode: "+886",
    label: "Taiwan",
    value: "Taiwan",
    flag: "🇹🇼",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    phoneCode: "+992",
    label: "Tajikistan",
    value: "Tajikistan",
    flag: "🇹🇯",
  },
  {
    name: "Tanzania",
    code: "TZ",
    phoneCode: "+255",
    label: "Tanzania",
    value: "Tanzania",
    flag: "🇹🇿",
  },
  {
    name: "Thailand",
    code: "TH",
    phoneCode: "+66",
    label: "Thailand",
    value: "Thailand",
    flag: "🇹🇭",
  },
  {
    name: "Togo",
    code: "TG",
    phoneCode: "+228",
    label: "Togo",
    value: "Togo",
    flag: "🇹🇬",
  },
  {
    name: "Tonga",
    code: "TO",
    phoneCode: "+676",
    label: "Tonga",
    value: "Tonga",
    flag: "🇹🇴",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    phoneCode: "+1868",
    label: "Trinidad and Tobago",
    value: "Trinidad and Tobago",
    flag: "🇹🇹",
  },
  {
    name: "Tunisia",
    code: "TN",
    phoneCode: "+216",
    label: "Tunisia",
    value: "Tunisia",
    flag: "🇹🇳",
  },
  {
    name: "Turkey",
    code: "TR",
    phoneCode: "+90",
    label: "Turkey",
    value: "Turkey",
    flag: "🇹🇷",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    phoneCode: "+993",
    label: "Turkmenistan",
    value: "Turkmenistan",
    flag: "🇹🇲",
  },
  {
    name: "Tuvalu",
    code: "TV",
    phoneCode: "+688",
    label: "Tuvalu",
    value: "Tuvalu",
    flag: "🇹🇻",
  },
  {
    name: "Uganda",
    code: "UG",
    phoneCode: "+256",
    label: "Uganda",
    value: "Uganda",
    flag: "🇺🇬",
  },
  {
    name: "Ukraine",
    code: "UA",
    phoneCode: "+380",
    label: "Ukraine",
    value: "Ukraine",
    flag: "🇺🇦",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    phoneCode: "+971",
    label: "United Arab Emirates",
    value: "United Arab Emirates",
    flag: "🇦🇪",
  },
  {
    name: "United Kingdom",
    code: "GB",
    phoneCode: "+44",
    label: "United Kingdom",
    value: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    name: "United States",
    code: "US",
    phoneCode: "+1",
    label: "United States",
    value: "United States",
    flag: "🇺🇸",
  },
  {
    name: "Uruguay",
    code: "UY",
    phoneCode: "+598",
    label: "Uruguay",
    value: "Uruguay",
    flag: "🇺🇾",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    phoneCode: "+998",
    label: "Uzbekistan",
    value: "Uzbekistan",
    flag: "🇺🇿",
  },
  {
    name: "Vanuatu",
    code: "VU",
    phoneCode: "+678",
    label: "Vanuatu",
    value: "Vanuatu",
    flag: "🇻🇺",
  },
  {
    name: "Vatican City",
    code: "VA",
    phoneCode: "+39",
    label: "Vatican City",
    value: "Vatican City",
    flag: "🇻🇦",
  },
  {
    name: "Venezuela",
    code: "VE",
    phoneCode: "+58",
    label: "Venezuela",
    value: "Venezuela",
    flag: "🇻🇪",
  },
  {
    name: "Vietnam",
    code: "VN",
    phoneCode: "+84",
    label: "Vietnam",
    value: "Vietnam",
    flag: "🇻🇳",
  },
  {
    name: "Yemen",
    code: "YE",
    phoneCode: "+967",
    label: "Yemen",
    value: "Yemen",
    flag: "🇾🇪",
  },
  {
    name: "Zambia",
    code: "ZM",
    phoneCode: "+260",
    label: "Zambia",
    value: "Zambia",
    flag: "🇿🇲",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    phoneCode: "+263",
    label: "Zimbabwe",
    value: "Zimbabwe",
    flag: "🇿🇼",
  },
];
