export default [
  {
    name: "Algeria",
    code: "DZ",
    phoneCode: "+213",
    label: "Algeria",
    value: "Algeria",
  },
  {
    name: "Angola",
    code: "AO",
    phoneCode: "+244",
    label: "Angola",
    value: "Angola",
  },
  {
    name: "Benin",
    code: "BJ",
    phoneCode: "+229",
    label: "Benin",
    value: "Benin",
  },
  {
    name: "Botswana",
    code: "BW",
    phoneCode: "+267",
    label: "Botswana",
    value: "Botswana",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    phoneCode: "+226",
    label: "Burkina Faso",
    value: "Burkina Faso",
  },
  {
    name: "Burundi",
    code: "BI",
    phoneCode: "+257",
    label: "Burundi",
    value: "Burundi",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    phoneCode: "+238",
    label: "Cabo Verde",
    value: "Cabo Verde",
  },
  {
    name: "Cameroon",
    code: "CM",
    phoneCode: "+237",
    label: "Cameroon",
    value: "Cameroon",
  },
  {
    name: "Central African Republic",
    code: "CF",
    phoneCode: "+236",
    label: "Central African Republic",
    value: "Central African Republic",
  },
  { name: "Chad", code: "TD", phoneCode: "+235", label: "Chad", value: "Chad" },
  {
    name: "Comoros",
    code: "KM",
    phoneCode: "+269",
    label: "Comoros",
    value: "Comoros",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    phoneCode: "+243",
    label: "Democratic Republic of the Congo",
    value: "Democratic Republic of the Congo",
  },
  {
    name: "Republic of the Congo",
    code: "CG",
    phoneCode: "+242",
    label: "Republic of the Congo",
    value: "Republic of the Congo",
  },
  {
    name: "Djibouti",
    code: "DJ",
    phoneCode: "+253",
    label: "Djibouti",
    value: "Djibouti",
  },
  {
    name: "Egypt",
    code: "EG",
    phoneCode: "+20",
    label: "Egypt",
    value: "Egypt",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    phoneCode: "+240",
    label: "Equatorial Guinea",
    value: "Equatorial Guinea",
  },
  {
    name: "Eritrea",
    code: "ER",
    phoneCode: "+291",
    label: "Eritrea",
    value: "Eritrea",
  },
  {
    name: "Eswatini",
    code: "SZ",
    phoneCode: "+268",
    label: "Eswatini",
    value: "Eswatini",
  },
  {
    name: "Ethiopia",
    code: "ET",
    phoneCode: "+251",
    label: "Ethiopia",
    value: "Ethiopia",
  },
  {
    name: "Gabon",
    code: "GA",
    phoneCode: "+241",
    label: "Gabon",
    value: "Gabon",
  },
  {
    name: "Gambia",
    code: "GM",
    phoneCode: "+220",
    label: "Gambia",
    value: "Gambia",
  },
  {
    name: "Ghana",
    code: "GH",
    phoneCode: "+233",
    label: "Ghana",
    value: "Ghana",
  },
  {
    name: "Guinea",
    code: "GN",
    phoneCode: "+224",
    label: "Guinea",
    value: "Guinea",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    phoneCode: "+245",
    label: "Guinea-Bissau",
    value: "Guinea-Bissau",
  },
  {
    name: "Ivory Coast",
    code: "CI",
    phoneCode: "+225",
    label: "Ivory Coast",
    value: "Ivory Coast",
  },
  {
    name: "Kenya",
    code: "KE",
    phoneCode: "+254",
    label: "Kenya",
    value: "Kenya",
  },
  {
    name: "Lesotho",
    code: "LS",
    phoneCode: "+266",
    label: "Lesotho",
    value: "Lesotho",
  },
  {
    name: "Liberia",
    code: "LR",
    phoneCode: "+231",
    label: "Liberia",
    value: "Liberia",
  },
  {
    name: "Libya",
    code: "LY",
    phoneCode: "+218",
    label: "Libya",
    value: "Libya",
  },
  {
    name: "Madagascar",
    code: "MG",
    phoneCode: "+261",
    label: "Madagascar",
    value: "Madagascar",
  },
  {
    name: "Malawi",
    code: "MW",
    phoneCode: "+265",
    label: "Malawi",
    value: "Malawi",
  },
  { name: "Mali", code: "ML", phoneCode: "+223", label: "Mali", value: "Mali" },
  {
    name: "Mauritania",
    code: "MR",
    phoneCode: "+222",
    label: "Mauritania",
    value: "Mauritania",
  },
  {
    name: "Mauritius",
    code: "MU",
    phoneCode: "+230",
    label: "Mauritius",
    value: "Mauritius",
  },
  {
    name: "Morocco",
    code: "MA",
    phoneCode: "+212",
    label: "Morocco",
    value: "Morocco",
  },
  {
    name: "Mozambique",
    code: "MZ",
    phoneCode: "+258",
    label: "Mozambique",
    value: "Mozambique",
  },
  {
    name: "Namibia",
    code: "NA",
    phoneCode: "+264",
    label: "Namibia",
    value: "Namibia",
  },
  {
    name: "Niger",
    code: "NE",
    phoneCode: "+227",
    label: "Niger",
    value: "Niger",
  },
  {
    name: "Nigeria",
    code: "NG",
    phoneCode: "+234",
    label: "Nigeria",
    value: "Nigeria",
  },
  {
    name: "Rwanda",
    code: "RW",
    phoneCode: "+250",
    label: "Rwanda",
    value: "Rwanda",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    phoneCode: "+239",
    label: "Sao Tome and Principe",
    value: "Sao Tome and Principe",
  },
  {
    name: "Senegal",
    code: "SN",
    phoneCode: "+221",
    label: "Senegal",
    value: "Senegal",
  },
  {
    name: "Seychelles",
    code: "SC",
    phoneCode: "+248",
    label: "Seychelles",
    value: "Seychelles",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    phoneCode: "+232",
    label: "Sierra Leone",
    value: "Sierra Leone",
  },
  {
    name: "Somalia",
    code: "SO",
    phoneCode: "+252",
    label: "Somalia",
    value: "Somalia",
  },
  {
    name: "South Africa",
    code: "ZA",
    phoneCode: "+27",
    label: "South Africa",
    value: "South Africa",
  },
  {
    name: "South Sudan",
    code: "SS",
    phoneCode: "+211",
    label: "South Sudan",
    value: "South Sudan",
  },
  {
    name: "Sudan",
    code: "SD",
    phoneCode: "+249",
    label: "Sudan",
    value: "Sudan",
  },
  {
    name: "Tanzania",
    code: "TZ",
    phoneCode: "+255",
    label: "Tanzania",
    value: "Tanzania",
  },
  { name: "Togo", code: "TG", phoneCode: "+228", label: "Togo", value: "Togo" },
  {
    name: "Tunisia",
    code: "TN",
    phoneCode: "+216",
    label: "Tunisia",
    value: "Tunisia",
  },
  {
    name: "Uganda",
    code: "UG",
    phoneCode: "+256",
    label: "Uganda",
    value: "Uganda",
  },
  {
    name: "Zambia",
    code: "ZM",
    phoneCode: "+260",
    label: "Zambia",
    value: "Zambia",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    phoneCode: "+263",
    label: "Zimbabwe",
    value: "Zimbabwe",
  },
];
