export default [
  {
    code: "USD",
    name: "United States Dollar",
    country: "United States",
    flag: "🇺🇸",
    symbol: "$",
  },
  {
    code: "EUR",
    name: "Euro",
    country: "Eurozone",
    flag: "🇪🇺",
    symbol: "€",
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    country: "Japan",
    flag: "🇯🇵",
    symbol: "¥",
  },
  {
    code: "GBP",
    name: "British Pound",
    country: "United Kingdom",
    flag: "🇬🇧",
    symbol: "£",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    country: "Australia",
    flag: "🇦🇺",
    symbol: "A$",
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    country: "Canada",
    flag: "🇨🇦",
    symbol: "C$",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    country: "Switzerland",
    flag: "🇨🇭",
    symbol: "CHF",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    country: "China",
    flag: "🇨🇳",
    symbol: "¥",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    country: "Sweden",
    flag: "🇸🇪",
    symbol: "kr",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    country: "New Zealand",
    flag: "🇳🇿",
    symbol: "NZ$",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    country: "Ghana",
    flag: "🇬🇭",
    symbol: "₵",
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    country: "Nigeria",
    flag: "🇳🇬",
    symbol: "₦",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    country: "India",
    flag: "🇮🇳",
    symbol: "₹",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    country: "Brazil",
    flag: "🇧🇷",
    symbol: "R$",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    country: "Russia",
    flag: "🇷🇺",
    symbol: "₽",
  },
  {
    code: "ZAR",
    name: "South African Rand",
    country: "South Africa",
    flag: "🇿🇦",
    symbol: "R",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    country: "Turkey",
    flag: "🇹🇷",
    symbol: "₺",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    country: "Mexico",
    flag: "🇲🇽",
    symbol: "MX$",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    country: "Singapore",
    flag: "🇸🇬",
    symbol: "S$",
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    country: "Hong Kong",
    flag: "🇭🇰",
    symbol: "HK$",
  },
  {
    code: "KRW",
    name: "South Korean Won",
    country: "South Korea",
    flag: "🇰🇷",
    symbol: "₩",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    country: "Malaysia",
    flag: "🇲🇾",
    symbol: "RM",
  },
  {
    code: "THB",
    name: "Thai Baht",
    country: "Thailand",
    flag: "🇹🇭",
    symbol: "฿",
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    country: "Indonesia",
    flag: "🇮🇩",
    symbol: "Rp",
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    country: "Vietnam",
    flag: "🇻🇳",
    symbol: "₫",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    country: "Philippines",
    flag: "🇵🇭",
    symbol: "₱",
  },
  {
    code: "AED",
    name: "United Arab Emirates Dirham",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    symbol: "د.إ",
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    symbol: "﷼",
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    country: "Egypt",
    flag: "🇪🇬",
    symbol: "£",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    country: "Norway",
    flag: "🇳🇴",
    symbol: "kr",
  },
  {
    code: "DKK",
    name: "Danish Krone",
    country: "Denmark",
    flag: "🇩🇰",
    symbol: "kr",
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    country: "Poland",
    flag: "🇵🇱",
    symbol: "zł",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    country: "Hungary",
    flag: "🇭🇺",
    symbol: "Ft",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    country: "Czech Republic",
    flag: "🇨🇿",
    symbol: "Kč",
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    country: "Israel",
    flag: "🇮🇱",
    symbol: "₪",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    country: "Argentina",
    flag: "🇦🇷",
    symbol: "AR$",
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    country: "Chile",
    flag: "🇨🇱",
    symbol: "CLP$",
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    country: "Peru",
    flag: "🇵🇪",
    symbol: "S/",
  },
  {
    code: "COP",
    name: "Colombian Peso",
    country: "Colombia",
    flag: "🇨🇴",
    symbol: "COP$",
  },
];
